version: "3"
services:
    vector:
        image: hamropatrorepo/vector:12021-04-07
        environment:
            - METRICS_URL=http://router:8000/metrics
            - AUTO_REBALANCE_URL=http://router:8000/auto-rebalance
            - ADMIN_TOKEN=cxt1234
        ports:
            - 8080:8080
